import type { Profile } from "./types";

export const profiles: Profile[] = [
  {
    slug: "cascade-canna",
    name: "Cascade Canna Co.",
    role: "Brand",
    location: "Portland, Oregon",
    description: "Small-batch edibles built for dependable retail velocity.",
    specialties: ["Edibles", "Wholesale", "Woman-owned"],
    verified: true,
    initials: "CC",
  },
  {
    slug: "harbor-dispensary",
    name: "Harbor Dispensary",
    role: "Dispensary",
    location: "Baltimore, Maryland",
    description: "Community-first dispensary seeking premium regional partners.",
    specialties: ["Retail", "Education", "Maryland"],
    verified: true,
    initials: "HD",
  },
  {
    slug: "northstar-sales",
    name: "Northstar Sales Group",
    role: "Sales rep",
    location: "Chicago, Illinois",
    description: "Multi-state representation for emerging cannabis operators.",
    specialties: ["Distribution", "B2B", "Midwest"],
    verified: false,
    initials: "NS",
  },
  {
    slug: "mosaic-market",
    name: "Mosaic Market",
    role: "Retailer",
    location: "Phoenix, Arizona",
    description: "A curated retail network focused on trusted customer experiences.",
    specialties: ["Retail", "Multi-location", "Arizona"],
    verified: true,
    initials: "MM",
  },
  {
    slug: "greenline-goods",
    name: "Greenline Goods",
    role: "Brand",
    location: "Trenton, New Jersey",
    description: "Modern wellness products with transparent sourcing.",
    specialties: ["Wellness", "CBD", "New Jersey"],
    verified: true,
    initials: "GG",
  },
  {
    slug: "union-street",
    name: "Union Street Collective",
    role: "Dispensary",
    location: "Boston, Massachusetts",
    description: "Independent operator building a stronger local supply chain.",
    specialties: ["Retail", "Local", "Massachusetts"],
    verified: false,
    initials: "US",
  },
];
